server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://39.97.248.91:3306/onlineTest_db?useUnicode=true&characterEncoding=utf8
    username: root
    password: root123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /**


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kiven.onlinetest.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.kevin.onlinetest: debug
